apiVersion: v1
kind: Service
metadata:
  name: nk-portfolio-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    name: nk-portfolio
